#Mssql DB
server: "196.1.115.155"
user: "AEMobile"
password: "a$m0bil@2015"
port: "1433"
database: "AE_AMX_Mobile"

segments_allowed: "nse_fo,nse_cm,bse_cm,cde_fo,ncx_fo,mcx_fo"

nse_series: "EQ,BE,BZ,GB,E1,RR,IV,SM,ST"
bse_series: "A,SM,ST,RR"
index_instruments: "COMDTY,UNDCUR"

uat :
    userID: "MSILADMNU"
    password: "UAT#$111"
    
env: "uat"
